### ISSUE TITLE
GamepadTest Broken on Windows

### ISSUE THREAD

**Issue by diegomachado** [HaxeFlixel/flixel-demos#198]
I'm on Windows using a XBox 360 Controller and building C++ targets, using the latest stable release from haxelib (3.3.11).

Right stick works only on the left part, Start is mapped to LB and X/Y/A/B somehow are mapped to DPad and other issues.

**Comment by larsiusprime** [comment]
Can you show a screenshot of the demo? And can you confirm these two points:

1) You are using a real Microsoft Xbox 360 controller (and not a knockoff that might have other inputs)
2) Flixel is identifying your controller as the above (screenshot will verify this)

**Comment by diegomachado** [comment]
1) Yes, a original Xbox 360 Controller
2) Flixel is identifying it correctly because Flash and Mac builds are working just fine 
3) This issue is from latest release from haxelib

I'm desperate to finish a entry for a jam, so I removed the released version and instaled the one from dev branch. But the screenshot I would give you would be just the 'old' GamePadTest demo (http://haxeflixel.com/demos/GamepadTest/)

Dev branch's new GamepadTest works perfectly, and the hosted demo at haxeflixel.com works fine as well. Maybe some openFL update broke the old version?

**Comment by larsiusprime** [comment]
Alright, so the legacy inputs for the Xbox 360 are wrong perhaps.... I'm sorry that I don't know how to fix those as I've only ever worked on the dev branch. Wonder if someone else can help.

**Comment by diegomachado** [comment]
Ok @larsiusprime, thank you soo much for this and everything you've been doing for HaxeFlixel.

**Comment by larsiusprime** [comment]
Sanity check for when help arrives: what versions of OpenFL and Lime are you using? What do you see in haxelib list?

**Comment by diegomachado** [comment]
lime: [2.5.2]
openfl: [3.2.2]

**Comment by larsiusprime** [comment]
Just so you know, we investigated this on Slack chat, we'll try to get a patch out but here's the transcript in the meantime:

> jahndis [5:19 PM]
So I was able to figure out which keycodes are correct for all of the buttons (A,X,Y,B,LB,RB,Start,Back,RightAnalog,LeftAnalog,XBOX), however it looks like, on windows cpp, there aren't key codes for the DPAD (also known as the hat) but those values can be read via FlxGamePad.hat or dpadUp,dpadDown,etc. (although for some reason, I'm not seeing these values in the api docs? maybe they are post 3.3.9?)
In addition (to make things more confusing) the axis codes for the left and right analogs were incorrect, and LTrigger and RTrigger operate on a 3rd axis. Here are the codes I determined:
A: 0

> jahndis [5:19 PM]
A:0, B:1, X:2, Y:3, LB: 4, RB: 5, Back:6, Start:7, LAnalog:8, RAnalog:9, XBOX:10

> jahndis [5:21 PM]
DPAD can be read from the variables I referenced (as of 3.3.11 at least) and the axis codes are:
LAnalogX: 0, LAnalogY: 1, RAnalogX: 3, RAnalogY: 4, LTrigger: 2, RTrigger: 5

> jahndis [5:22 PM]
so the value can be obtained with FlxGamePad.getXAxis(<code>) and getYAxis()

> jahndis [5:23 PM]
I have to head out for a while now, but I would imagine just editing the XboxButtonID class to reflect these values would be enough. I also just substituted 11, 12, 13, and 14 in for the DPAD values because I didn't really know what to put there

> jahndis [5:25 PM]
but it seems the GamePad demo also needs to be updated for non flash targets to use the .hat values rather than DPAD button codes.

This is why we had the huge refactor of gamepad stuff in the dev branch, which makes everything so much nicer. Now we just need to actually get around to releasing dev branch of course...

**Comment by diegomachado** [comment]
That's great and you guys are awesome.

I knew that was all fixed in dev branch, but it's important to bring and fix that up so beginners don't get frustrated. Thanks again @larsiusprime.

**Comment by Froom7** [comment]
Is this issue already been fixed? I'm using Flixel 3.3.11 and Lime 2.7.0
It's kinda frustrating that the Xbox controller is still broken on Windows platform. I'm kinda scared to use the dev version of Flixel. So I hope this issue will be resolved soon!

**Comment by Gama11** [comment]
Duplicate of HaxeFlixel/flixel#1573.
